### ISSUE TITLE
فاز دوم

### ISSUE THREAD

**Issue by mani1381** [AdvancedProgrammingSUT2022/project-group-11#3]

**Comment by mani1381** [comment]
<div dir="rtl" align='right'>

# فاز2
**نام و نام خانوادگی راهنما: امیررضا ابوطالبی**

</details>

## تسک‌های نفر اول

  **نام و نام خانوادگی: تارا رضایی**
<details>
  <summary>تسک مربوطه</summary>
 گرافیکی کردن منو های بازی شامل لاگین، ساین آپ


  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- پیاده سازی گرافیک منوی پروفایل
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
-  پیاده سازی گرافیک شهر و سیتی پنل
 

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [ ] در حال انجام
  3. [ ] تمام شده
  </div>
کامل کردن منطق کامبت


  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

## تسک‌های نفر دوم

  **نام و نام خانوادگی: احسان نادری**
<details>
  <summary>تسک مربوطه</summary>
- مپ دستی


  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
- سیو بازی
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
-  چت روم

  <div dir="ltr" align='right'>

  1. [x] شروع نشده
  2. [ ] در حال انجام
  3. [ ] تمام شده
  </div>

</details>


## تسک‌های نفر سوم

  **نام و نام خانوادگی: مانی تهامی**
<details>
  <summary>تسک مربوطه</summary>
- گیم منو
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- جدول امتیازات
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- نمایش نقشه
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- فاگ آو وار
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- اینفو پنل
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- بیلدینگ
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- گرافیک یونیت
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- گرافیک ورکرز
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- تکنولوژی تری
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- حالت تقلب
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- دیپلماسی
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- برد و باخت
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>

</details>
</div>

**Comment by essi2002** [comment]
###

**Comment by essi2002** [comment]
tamam

**Comment by TaraRK** [comment]
.
