### ISSUE TITLE
فاز۳

### ISSUE THREAD

**Issue by mani1381** [AdvancedProgrammingSUT2022/project-group-11#4]

**Comment by mani1381** [comment]
<div dir="rtl" align='right'>

# فاز۳
**نام و نام خانوادگی راهنما: امیررضا ابوطالبی**

</details>

## تسک‌های نفر اول

  **نام و نام خانوادگی: تارا رضایی**
<details>
  <summary>تسک مربوطه</summary>
 
سرور کلاینت کردن لابی

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
سرور کلاینت کردن دوستی

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

## تسک‌های نفر دوم

  **نام و نام خانوادگی: احسان نادری**
<details>
  <summary>تسک مربوطه</summary>
- گلوبال چت


  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- منوهای بازی


  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [x] در حال انجام
  3. [x] تمام شده
  </div>
- لاجیک کلی سرور کلاینت


  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>


## تسک‌های نفر سوم

  **نام و نام خانوادگی: مانی تهامی**
<details>
  <summary>تسک مربوطه</summary>
- جدول امتیازات 
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>

- لاگین
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
- دیباگ کردن
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
</div>

**Comment by essi2002** [comment]
tamammm

**Comment by essi2002** [comment]
commit changes

**Comment by TaraRK** [comment]
done
